# 
base_url: "https://projects.lib.utah.edu:8443"
search_url: "search?jql=project%20%3D%20PR%20AND%20status%20%3D%20Open%20AND%20createdDate%20>%202022-1-23"
printing_url: search?jql=project%20%3D%20PR%20AND%20status%20%3D%20\"In%20Progress\""
#jira login information
jira_user: "ehsl_client"
jira_password: "asdqwe123"
tickerStartString: "EHSL3DPR-"
Make_files_anon: True #This changes the file names so that we don't know exactly what is printing unless you look at the file.
Save_printed_files: True#this lets us save some extra information but is also less secure on a privacy front.
use_nice_list: False #if you want an opt-in only printing service you could have people in this list.
use_naughty_list: True #When someone is bad you can auto reject uses by adding them into this list.
updateRate: 1 #Time in minutes that it refreshed the jira and octoprint calls.

messages:
    printStarted: "Your file is now printing and we will update you when it is finished and ready for pickup"
    printFinished: "Your print has been completed and should now be available for pickup"
    finalMessage: "\n\nYour link to pay online will be generated by my supervisor as soon as they are available. Your print is ready for pickup by the orange pillars in the ProtoSpace on the 2nd floor of the library whenever the library is open. Thanks!"
    taxExemptFinalMessage: " (tax exempt)\n\nYour print is ready for pickup by the orange pillars in the ProtoSpace on the 2nd floor of the library whenever the library is open. Thanks!"
    wrongConfig: "Please follow the slicing instructions and re-submit. Our automated check suggests you did not use our slicer configs"
    downloadedFile: "Your print file has been downloaded and is now in the print queue."
    noFile: "Please try again and make sure to upload a file, if your file is larger than 25mb then paste a google drive share link in the description of the print"
    statusUpdate: "Your print stats: "
    statusUpdateEnd: ""
    statusInQueue: "We have your file and it is in the print queue, we will send your another message when your print has started on a printer and again when the print is ready for pick-up. You can request a status update anytime by commenting \"status update\" "
    stopMessage: "Due to your request your print has stopped printing."
    
requestUpdate:
    update: "update"
    status: "status"
    
requestStop:
    update: "Kill my print"
    status: "Stop my print"
    
# this will be used more later #
payment:
    url: ""
    username: ""
    password: ""
    apikey: ""
    prepay: False
    costPerGram: 0.05 # This means we are charging 5¢ per gram of material
    tax: 1.0775 # The sales tax rate in utah as the time of this comment

# this is a very specific section if you have it you know #
receipt_printer:
    print_physical_receipt: True
    ID: "(0x0416, 0x5011, 0, 0x81, 0x03)"

#Structure of check items:

#    - command: 'EXAMPLE' # ';' for a comment, 'M73' or something for a different command
#      checkAction: 'EXAMPLE' # Comes from enumDefinitions GcodeCheckActions
#      actionValue:
#        - 'EXAMPLE' # Contains the information associated with a command. For instance, for M0 you could put 'Done?' as the actionValue.
#        - 'EXAMPLE2' # This is a list of parameters for the command. Each will be added after the command with a space between them.

gcodeCheckItems:
          # Remove unwanted M0's
        - command: "M0"
          checkAction: "REMOVE_COMMAND_ALL"

          # Remove M300
        - command: "M300"
          checkAction: "REMOVE_COMMAND_ALL"

          # Add the M0 we want.
        - command: "M0"
          checkAction: "ADD_COMMAND_AT_END"
          actionValue:
            - "Done?"

          # Make sure a homing command exists.
        - command: "G28"
          checkAction: "COMMAND_MUST_EXIST"

          # Check that MLIB exists (This should be made better)
        - command: ";"
          checkAction: "COMMAND_MUST_EXIST"
          actionValue:
            - "MLIB profile version 2."

          # Set max nozzle temps
        - command: "M104"
          checkAction: "COMMAND_PARAM_MAX"
          actionValue:
            - "205"
        - command: "M109"
          checkAction: "COMMAND_PARAM_MAX"
          actionValue:
            - "205"

          # Set max bed temps
        - command: "M140"
          checkAction: "COMMAND_PARAM_MAX"
          actionValue:
            - "60"
        - command: "M190"
          checkAction: "COMMAND_PARAM_MAX"
          actionValue:
            - "60"
