base_url: "https://projects.lib.utah.edu:8443"
search_url: "search?jql=project%20%3D%20ED%20AND%20status%20%3D%20Open"
link_to_canvas_class: ""
contact_info: ""
jira_user: "ehsl_client"
jira_password: "asdqwe123"
Make_files_anon: True
Save_printed_files: False
use_nice_list: False
use_naughty_list: True

payment:
    url: ""
    username: ""
    password: ""
    apikey: ""
    prepay: False

reciept_printer:
    print_physical_reciept: False
    ID: "(0x0416, 0x5011, 0, 0x81, 0x03)"
    Note: "I dont't have one of these so I can't really test it and am not sure what is needed so we will make a new function that will take this into account"

gcode_check_text:
    startGcode: "G28"
    endGcode: "M0"
    material: "M1"
    printer: "Prusa"
    notes_print_settings: "EHSL"
    before_layer_change: ""
    after_layer_change: ""
    tool_change: ""
    between_objects: ""
    color_change: ""
    pause_print_gcode: ""
    template_custom_gcode: ""
    customChecks: true

custom_gcode_check:
    max_hotend: "210"
    max_bed: "65"
    minimum_profile_version: "1.2"
